### PR TITLE
Revert "add support for setting custom server ports"

### PR DESCRIPTION
**Pull request by wohahobg**
Reverts wohahobg/pterosync#36

### CODE REVIEW

**Comment by tylerforesthauser** [comment]
This didn't work out, after all?

**Comment by wohahobg** [comment]
It does I have added it.

**Comment by tylerforesthauser** [comment]
Oh ok, cool! I did want to inform you of something our team noticed, however. We needed to add an extra param to the `getServer` helper to also accommodate the server port...
```php
    public function getServer()
    {
        if (!$this->server) {
            $server = Capsule::table('tblservers')
                ->where('type', 'pterosync')
                ->first();
            $this->server = [
                'serverhostname' => $server->hostname,
                'serverusername' => $server->username,
                'serverpassword' => decrypt($server->password),
                'serveraccesshash' => $server->accesshash,
                'serversecure' => $server->secure,
                'serverport' => $server->port, // Makes it available when calling helper functions outside of module context (hooks, for instance)
            ];
        }
        return $this->server;
    }
  ```

**Comment by wohahobg** [comment]
Did you check if this `$server->port` exist in the database ?

**Comment by tylerforesthauser** [comment]
Yep, it does. If it was set, of course.

**Pull request merged**
